version: "3.8"

services:
  db:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U user -d mydb'",
        ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  app:
    build: .
    container_name: my_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_URL: postgres://user:password@db:5432/mydb?sslmode=disable
      MAIN_STORAGE: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
