CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  comments_allowed BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS posts_comments (
  post_id UUID REFERENCES posts (id) ON DELETE CASCADE,
  id UUID PRIMARY KEY,
  parent_id UUID NULL REFERENCES posts_comments (id) ON DELETE CASCADE,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  content VARCHAR(2000) NOT NULL
);