package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/Cheasezz/testForOzon/internal/gql/runtime"
)

// RepliesCount is the resolver for the repliesCount field.
func (r *commentResolver) RepliesCount(ctx context.Context, obj *core.Comment) (int, error) {
	// Резолвер для поля repliesCount в graphql типе Comment
	// Считает сколько комментов ссылается на родительскеий коммент (у них .parentId==obj.Id)
	count, err := r.env.Services.Comment.RepliesCount(ctx, obj.Id)
	if err != nil {
		return 0, err
	}
	return count, err
}

// Comment returns runtime.CommentResolver implementation.
func (r *Resolver) Comment() runtime.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
