package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/Cheasezz/testForOzon/internal/gql/runtime"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *core.Comment, limit *int, offset *int) ([]*core.Comment, error) {
	fmt.Println("Replies ComentResolver func call")

	if *limit > 50 {
		*limit = 50
	}
	replies, err := r.env.Services.Comment.GetReplies(ctx, obj, limit, offset)
	if err != nil {
		return nil, err
	}

	return replies, nil
}

// Comment returns runtime.CommentResolver implementation.
func (r *Resolver) Comment() runtime.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
