package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/google/uuid"
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, id *uuid.UUID, limit *int, offset *int) ([]*core.Post, error) {
	fmt.Println("Posts query resolver")
	// Не может быть загружено больше 50 постов за раз
	if *limit > 50 {
		*limit = 50
	}
	posts, err := r.env.Services.Post.GetPosts(ctx, id, limit, offset)
	if err != nil {
		return nil, err
	}
	return posts, nil
}
