package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/Cheasezz/testForOzon/internal/gql/runtime"
)

// Comments is the resolver for the comments field.
func (r *postWithCommentsResolver) Comments(ctx context.Context, obj *core.Post, limit *int, offset *int) ([]*core.Comment, error) {
	// Резолвер для поля comments в graphql типе PostWithComments
	// Загружает только рут коменты, т.е непосредственно коменты к посту, а не реплаи
	rootComments, err := r.env.Services.Comment.GetRootComments(ctx, obj.Id, *limit, *offset)
	if err != nil {
		return nil, err
	}
	return rootComments, err
}

// PostWithComments returns runtime.PostWithCommentsResolver implementation.
func (r *Resolver) PostWithComments() runtime.PostWithCommentsResolver {
	return &postWithCommentsResolver{r}
}

type postWithCommentsResolver struct{ *Resolver }
