package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/core"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input core.PostCreateInput) (*core.Post, error) {
	post, err := r.env.Services.Post.CreatePost(ctx, input)
	if err != nil {
		return nil, err
	}
	fmt.Println("CreatePost mutation resolver")
	return post, nil
}
