package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/Cheasezz/testForOzon/internal/gql/runtime"
)

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *core.Post, limit *int, offset *int) ([]*core.Comment, error) {
	fmt.Println("Comments PostResolver func call")
	if *limit > 50 {
		*limit = 50
	}
	comment, err := r.env.Services.Comment.GetRootComments(ctx, obj.Id, limit, offset)
	if err != nil {
		return nil, err
	}
	return comment, nil
}

// Post returns runtime.PostResolver implementation.
func (r *Resolver) Post() runtime.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
