package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/core"
	"github.com/Cheasezz/testForOzon/internal/gql/model"
)

// AllTests is the resolver for the allTests field.
func (r *testQueryResolver) AllTests(ctx context.Context, obj *model.TestQuery) ([]*core.Test, error) {
	fmt.Println("AllTests resolver")
	r.env.Services.Test.CheckTest(ctx)
	return []*core.Test{}, nil
}
