package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/Cheasezz/testForOzon/internal/gql/model"
	"github.com/Cheasezz/testForOzon/internal/gql/runtime"
)

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context) (*model.TestQuery, error) {
	fmt.Println("Test resolver")
	return &model.TestQuery{}, nil
}

// TestQuery returns runtime.TestQueryResolver implementation.
func (r *Resolver) TestQuery() runtime.TestQueryResolver { return &testQueryResolver{r} }

type testQueryResolver struct{ *Resolver }
