// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/Cheasezz/testForOzon/internal/core"
)

type Query struct {
}

type TestQuery struct {
	AllTests []*core.Test `json:"allTests"`
}
